File runnableJar = new File(basedir, 'target/test-enhance-ant-0-SNAPSHOT-run.jar')
assert runnableJar.exists()
File signal = new File(basedir, "target/signal.txt")
println("Executing " + runnableJar)
println([System.getProperty("java.home") + "/bin/java", "-jar", runnableJar.toString(), "-Dsignal.file="+signal.getAbsolutePath()].execute().text)
assert signal.exists()
File shutdownExecuted = new File(runnableJar.toString() + ".shutdown-was-called")
assert shutdownExecuted.exists()
